### ISSUE TITLE
Script working but displaying error during execution

### ISSUE THREAD

**Issue by fttdgc** [kompazz/gmail2mysql#1]
I installed the script and it's capturing the emails from gmail and bringing them to the db but it's also throwing up this error when I run it. 

`Traceback (most recent call last):
  File "gmail_to_mysql.py", line 200, in <module>
    main()
  File "gmail_to_mysql.py", line 189, in main
    box = gmail_login(settings, mailbox_name)
  File "gmail_to_mysql.py", line 19, in gmail_login
    imapper = e.connect(host, user, password, mailbox, ssl=True, read_only=True)
  File "/usr/local/lib/python3.8/site-packages/easyimap/easyimap.py", line 207,
in connect
    return Imapper(host, user, password, mailbox, timeout, ssl, port, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/easyimap/easyimap.py", line 145,
in __init__
    self._mailer = self._get_mailer(host, user, password, mailbox, timeout, ssl,
 port)
  File "/usr/local/lib/python3.8/site-packages/easyimap/easyimap.py", line 159,
in _get_mailer
    raise Exception("Timeout.")
Exception: Timeout.
`

**Comment by kompazz** [comment]
what's the console output preceding the exception?

**Comment by fttdgc** [comment]
To confirm, whenever there's a new message, it's still collecting and inserting it to the mysql database, it's just generating the error along with it.

`python3.8 gmail_to_mysql.py

Zalogowano do gmail
Zalogowano do mysql
Przetwarzam skrzynkę inbox. Maili do importu: 0
Traceback (most recent call last):
  File "gmail_to_mysql.py", line 200, in <module>
    main()
  File "gmail_to_mysql.py", line 189, in main
    box = gmail_login(settings, mailbox_name)
  File "gmail_to_mysql.py", line 19, in gmail_login
    imapper = e.connect(host, user, password, mailbox, ssl=True, read_only=True)
  File "/usr/local/lib/python3.8/site-packages/easyimap/easyimap.py", line 207, in connect
    return Imapper(host, user, password, mailbox, timeout, ssl, port, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/easyimap/easyimap.py", line 145, in __init__
    self._mailer = self._get_mailer(host, user, password, mailbox, timeout, ssl, port)
  File "/usr/local/lib/python3.8/site-packages/easyimap/easyimap.py", line 159, in _get_mail
er
    raise Exception("Timeout.")
Exception: Timeout.
`

**Comment by kompazz** [comment]
So this relates to the outbox. The problem with this is outbox name varies depending on the language. Currently it supports Polish outbox name. Can you provide your gmail language and the outbox name for your language?

**Comment by fttdgc** [comment]
English. The emails go to the Sent folder.

**Comment by fttdgc** [comment]
Even though it is 'Sent' on the website, it is 'Sent Mail' in imap. Changed "Wys&AUI-ane" to "Sent Mail" on line 93 and 175 from and it's working now. Thanks!

**Comment by kompazz** [comment]
Just added language to configuration file. Please verify if it works for you.

**Comment by fttdgc** [comment]
It looks like even though 'Sent' is the display on English accounts, 'Sent Mail' is the IMAP folder name

https://developers.google.com/gmail/imap/imap-extensions

With that in mind making the change to 'Sent Mail,' the python error is gone, though, upon completion it gives a gmail login error at the end. 

`Zalogowano do gmail
Zalogowano do mysql
Przetwarzam skrzynkę inbox. Maili do importu: 0
Błędne dane logowania gmail`

**Comment by kompazz** [comment]
Corrected the EN outbox name in settings.ini. Please check now
